swagger: "2.0"
info:
  title: packageの宣言
  version: version not set
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/info/account/{name}:
    get:
      summary: アカウント本の貸し出し日を取得
      operationId: LendingBooksService_GetBorrowedTime
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/myappBorrrowResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: name
          description: 借りる人の名前
          in: path
          required: true
          type: string
  /v1/info/book:
    post:
      summary: 新しい本を登録
      operationId: LendingBooksService_RegisterBook
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/myappRegisterBookResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/myappRegisterBookRequest'
  /v1/info/book/{title}:
    get:
      summary: 本の貸し出し情報を取得
      operationId: LendingBooksService_GetLendingInfo
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/myappAccounts'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: title
          description: 本のタイトル
          in: path
          required: true
          type: string
definitions:
  Book:
    type: object
    properties:
      title:
        type: string
        title: 本のタイトル
    title: 借りる本
  myappAccount:
    type: object
    properties:
      name:
        type: string
        title: 借りる人の名前
    title: 図書館のアカウント
  myappAccounts:
    type: object
    properties:
      accounts:
        type: array
        items:
          type: object
          $ref: '#/definitions/myappAccount'
        title: 借りる人の名前
    title: 図書館のアカウント
  myappBorrrowResponse:
    type: object
    properties:
      account:
        $ref: '#/definitions/myappAccount'
        title: 本を借りたアカウント
      book:
        $ref: '#/definitions/Book'
        title: 借りた本
      timestamp:
        type: string
        format: date-time
        title: 貸し出し日
  myappRegisterBookRequest:
    type: object
    properties:
      num:
        type: integer
        format: int64
        title: 冊数
      title:
        type: string
        title: 登録する本のタイトル
    title: 本の登録リクエスト
  myappRegisterBookResponse:
    type: object
    properties:
      num:
        type: integer
        format: int64
        title: 冊数
      title:
        type: string
        title: 登録された本のタイトル
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
